FROM rhel7:7.5

LABEL \
      com.redhat.component="insights-ocp-scanner-container" \
      name="containers/insights-ocp-scanner" \
      version="0.0.1" 

RUN yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical --setopt=tsflags=nodocs && \
    yum install -y golang && \
    yum install -y insights-client && \
    yum install -y insights-ocp-scanner && \
    yum clean all

ENV EGG=/etc/insights-client/rpm.egg

ENTRYPOINT ["/usr/bin/insights-ocp-scanner"]